In [1]:
import h5py
import sys
import os
import csv
import math
import numpy as np

In [9]:
f = h5py.File('input/3.hdf5', 'r')
# List of device groups
deviceList = list(f.keys())
print(deviceList)
# Device 1
device = f[deviceList[0]]
print(device)
# Position dataset of device 1
dataset = device['Position']
print(dataset)
# Dataset of sample 1 of device 1
sample1Dataset = dataset[:, 0, :]
for sample in sample1Dataset:
    print(sample)

['Device_792888129_0']
<HDF5 group "/Device_792888129_0" (9 members)>
<HDF5 dataset "Position": shape (238, 1, 3), type "<f4">
[ 173.50465  -299.3472    -35.930164]
[ 173.52911  -299.33224   -35.944824]
[ 173.453   -299.35672  -35.94321]
[ 173.5128   -299.3199    -35.882572]
[ 173.41034  -299.3863    -35.808567]
[ 173.45923  -299.3633    -35.841896]
[ 173.37463 -299.41373  -35.79964]
[ 173.34319  -299.42834   -35.812756]
[ 173.41931 -299.39294  -35.70993]
[ 173.41907 -299.3875   -35.70444]
[ 173.4188   -299.37012   -35.695576]
[ 173.36111  -299.408     -35.556484]
[ 173.36264  -299.4016    -35.587555]
[ 173.42456 -299.36755  -35.55636]
[ 173.39943  -299.40393   -35.574917]
[ 173.4112   -299.3845    -35.656998]
[ 173.37386  -299.4274    -35.668472]
[ 173.37625  -299.4055    -35.721718]
[ 173.37386 -299.42502  -35.58267]
[ 173.40457 -299.39557  -35.53187]
[ 173.38164 -299.41977  -35.61274]
[ 173.43219 -299.40695  -35.71257]
[ 173.43459  -299.41574   -35.842995]
[ 173.36777 -299.45117  -3

In [6]:
csv_file = 'text.csv'
shape = dataset.shape
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    for i in range(shape[1]):
        writer.writerows(dataset[:,0,:])

In [7]:
class OutputDictionary:
    def __init__(self):
        self.data = {}
    
    def addFile(self, filename):
        self.data[filename] = []
    
    def addDeviceAvg(self, filename, deviceName, avgList):
        deviceDict = {deviceName: avgList}
        self.data[filename].append(deviceDict)
    
    def __str__(self):
        return str(self.data)

In [8]:
nest = OutputDictionary()
nest.addFile("1.hdf5")
nest.addDeviceAvg("1.hdf5", "lights", [23, 54, 65])
nest.addDeviceAvg("1.hdf5", "BAR", [232, 544, 625])
nest.addFile("2.hdf5")
nest.addDeviceAvg("2.hdf5", "arm", [33, 56, 67])
print(nest)

{'1.hdf5': [{'lights': [23, 54, 65]}, {'BAR': [232, 544, 625]}], '2.hdf5': [{'arm': [33, 56, 67]}]}


Max Distance Test

In [36]:
class Sample:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
sampleList = []

fileH = h5py.File('input/3.hdf5', 'r')
deviceList = list(fileH.keys())
# Loops through device groups in file
for device in deviceList:
    # Checks if device has Position dataset
    tempDevice = fileH[device]
    if 'Position' in tempDevice:
        positionDataset = tempDevice['Position']
        shape = positionDataset.shape
        # Loops through each sensor in the device
        sensorIndex = 1
        for i in range(shape[sensorIndex]):
            sensorDataset = positionDataset[:, i, :]
            for sample in sensorDataset:
                point = Sample(sample[0], sample[1], sample[2])
                sampleList.append(point)

def euclideanDistance(sample1, sample2):
    x1, y1, z1 = sample1.x, sample1.y, sample1.z
    x2, y2, z2 = sample2.x, sample2.y, sample2.z
    squaredDistance = (x2 - x1)**2 + (y2-y1)**2 + (z2-z1)**2
    return math.sqrt(squaredDistance)

In [17]:
index = []
def maxDistance(sampleList):
    n = len(sampleList)
    maxDistance = 0
 
    # Iterate over all possible pairs
    for i in range(n):
        for j in range(i + 1, n):
            temp = [sampleList[i].x, sampleList[i].y, sampleList[i].z, sampleList[j].x, sampleList[j].y, sampleList[j].z]
            # Update maxm
            tempMax = euclideanDistance(sampleList[i], sampleList[j])
            if tempMax > maxDistance:
                maxDistance = tempMax
                index = temp
                print(index)
    return maxDistance

print(maxDistance(sampleList))
print(index)

[173.50465, -299.3472, -35.930164, 173.52911, -299.33224, -35.944824]
[173.50465, -299.3472, -35.930164, 173.453, -299.35672, -35.94321]
[173.50465, -299.3472, -35.930164, 173.5128, -299.3199, -35.882572]
[173.50465, -299.3472, -35.930164, 173.41034, -299.3863, -35.808567]
[173.50465, -299.3472, -35.930164, 173.37463, -299.41373, -35.79964]
[173.50465, -299.3472, -35.930164, 173.34319, -299.42834, -35.812756]
[173.50465, -299.3472, -35.930164, 173.41931, -299.39294, -35.70993]
[173.50465, -299.3472, -35.930164, 173.41907, -299.3875, -35.70444]
[173.50465, -299.3472, -35.930164, 173.4188, -299.37012, -35.695576]
[173.50465, -299.3472, -35.930164, 173.36111, -299.408, -35.556484]
[173.50465, -299.3472, -35.930164, 173.40457, -299.39557, -35.53187]
[173.50465, -299.3472, -35.930164, 173.32732, -299.4678, -36.30635]
[173.50465, -299.3472, -35.930164, 173.93782, -299.03275, -36.13095]
[173.50465, -299.3472, -35.930164, 173.81682, -299.112, -36.35122]
[173.453, -299.35672, -35.94321, 173.937

In [37]:
minValue = 0
for sample in sampleList:
    if sample.x < minValue:
        minValue = sample.x
    if sample.y < minValue:
        minValue = sample.y
    if sample.z < minValue:
        minValue = sample.z
minValue = abs(minValue)
for i in range(len(sampleList)):
    sampleList[i].x += minValue
    sampleList[i].y += minValue
    sampleList[i].z += minValue

minSumIndex = sampleList[0]
minSum = 5000
maxSumIndex = sampleList[1]
maxSum = 0
for sample in sampleList:
    temp = sample.x + sample.y + sample.z
    if temp < minSum:
        minSum = temp
        minSumIndex = sample
    if temp > maxSum:
        maxSum = temp
        maxSumIndex = sample
minSumIndex.x -= minValue
minSumIndex.y -= minValue
minSumIndex.z -= minValue
maxSumIndex.x -= minValue
maxSumIndex.y -= minValue
maxSumIndex.z -= minValue

print(euclideanDistance(minSumIndex, maxSumIndex))

0.8641575086977477


Rotating Calipers Method

In [ ]:
# Object used to represent a 3d sample point
class SamplePoint:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

def dist(p, q):
    return (p.x - q.x) ** 2 + (p.y - q.y) ** 2 + (p.z - q.z) ** 2

def absArea(p, q, r):
    return abs((p.x * q.y + q.x * r.y + r.x * p.y) -
               (p.y * q.x + q.y * r.x + r.y * p.x))

Create DataSet

In [4]:
# Step 1: Create a new HDF5 file
file = h5py.File('testinput/devices.hdf5', 'w')

# Step 2: Define device names
devices = ['Device1', 'Device2', 'Device3', 'Device4', 'Device5']

datasets = ['Gyro', 'Accel', 'Indicator', 'Mag', 'Position']

# Step 3: Create groups for each device and populate with datasets
for device_name in devices:
    device_group = file.create_group(device_name)

    for i in range(len(datasets)):
        dataset_data = np.random.rand(1000, 2, 3)
        device_group.create_dataset(datasets[i], data=dataset_data)
file.close()

In [5]:
f = h5py.File('testinput/devices.hdf5', 'r')
# List of device groups
deviceList = list(f.keys())
print(deviceList)
# Device 1
device = f[deviceList[0]]
print(device)
# Position dataset of device 1
dataset = device['Position']
print(dataset)
# Dataset of sample 1 of device 1
sample1Dataset = dataset[:, 0, :]
sampleNum = 0
xSum = 0
ySum = 0
zSum = 0
for sample in sample1Dataset:
    sampleNum += 1
    xSum += sample[0]
    ySum += sample[1]
    zSum += sample[2]
print(xSum/sampleNum)
print(ySum/sampleNum)
print(zSum/sampleNum)

['Device1', 'Device2', 'Device3', 'Device4', 'Device5']
<HDF5 group "/Device1" (5 members)>
<HDF5 dataset "Position": shape (1000, 2, 3), type "<f8">
0.5080309874398369
0.47589502537644707
0.49707141156492873


In [7]:
# Step 1: Create a new HDF5 file
file = h5py.File('testinput/device3.hdf5', 'w')

# Step 2: Define device names
devices = ['Device1', 'Device4', 'Device5']

datasets = ['Gyro', 'Accel', 'Indicator', 'Mag']

# Step 3: Create groups for each device and populate with datasets
for device_name in devices:
    device_group = file.create_group(device_name)

    for i in range(len(datasets)):
        dataset_data = np.random.rand(1000, 3, 3)
        device_group.create_dataset(datasets[i], data=dataset_data)
file.close()